# Generated by Django 3.1.1 on 2020-09-20 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('exception_flg', models.BooleanField(null=True)),
            ],
            options={
                'unique_together': {('account_id', 'date')},
            },
        ),
    ]
